# Generated by Django 5.1.2 on 2024-11-05 16:13

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestion',
            name='boys_sect',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('Lubavitch', 'Lubavitch'), ('Litvish', 'Litvish'), ('Sefardi', 'Sefardi'), ('Yeshivish', 'Yeshivish'), ('Chassidish', 'Chassidish'), ('Bobov', 'Bobov'), ('Ger', 'Ger'), ('Belz', 'Belz'), ('Breslov', 'Breslov'), ('rachmastrivka', 'rachmastrivka'), ('Satmar', 'Satmar'), ('Skver', 'Skver'), ('Viznitz', 'Viznitz'), ('Modern Orthodox', 'Modern Orthodox'), ('Conservative', 'Conservative'), ('Other', 'Other')], max_length=50), blank=True, default=list, size=None),
        ),
        migrations.AddField(
            model_name='suggestion',
            name='girls_sect',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('Lubavitch', 'Lubavitch'), ('Litvish', 'Litvish'), ('Sefardi', 'Sefardi'), ('Yeshivish', 'Yeshivish'), ('Chassidish', 'Chassidish'), ('Bobov', 'Bobov'), ('Ger', 'Ger'), ('Belz', 'Belz'), ('Breslov', 'Breslov'), ('rachmastrivka', 'rachmastrivka'), ('Satmar', 'Satmar'), ('Skver', 'Skver'), ('Viznitz', 'Viznitz'), ('Modern Orthodox', 'Modern Orthodox'), ('Conservative', 'Conservative'), ('Other', 'Other')], max_length=50), blank=True, default=list, size=None),
        ),
    ]
