# Generated by Django 5.1.2 on 2024-11-07 03:18

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match_app', '0002_suggestion_boys_sect_suggestion_girls_sect'),
    ]

    operations = [
        migrations.AddField(
            model_name='suggestion',
            name='status',
            field=models.IntegerField(blank=True, choices=[(0, 'Active - Email Sent'), (1, 'Not Active - Suggestion Flagged')], null=True),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='boys_sect',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('Lubavitch', 'Lubavitch'), ('Litvish', 'Litvish'), ('Sefardi', 'Sefardi'), ('Yeshivish', 'Yeshivish'), ('Chassidish', 'Chassidish'), ('Bobov', 'Bobov'), ('Ger', 'Ger'), ('Belz', 'Belz'), ('Breslov', 'Breslov'), ('Rachmastrivka', 'Rachmastrivka'), ('Satmar', 'Satmar'), ('Skver', 'Skver'), ('Viznitz', 'Viznitz'), ('Modern Orthodox', 'Modern Orthodox'), ('Karlin-Stolin', 'Karlin-Stolin'), ('Toldos Aharon', 'Toldos Aharon'), ('Sanz', 'Sanz'), ('Pupa', 'Pupa'), ('Klausenburg', 'Klausenburg'), ('Bostoner', 'Bostoner'), ('Other', 'Other')], max_length=50), blank=True, default=list, size=None),
        ),
        migrations.AlterField(
            model_name='suggestion',
            name='girls_sect',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(choices=[('Lubavitch', 'Lubavitch'), ('Litvish', 'Litvish'), ('Sefardi', 'Sefardi'), ('Yeshivish', 'Yeshivish'), ('Chassidish', 'Chassidish'), ('Bobov', 'Bobov'), ('Ger', 'Ger'), ('Belz', 'Belz'), ('Breslov', 'Breslov'), ('Rachmastrivka', 'Rachmastrivka'), ('Satmar', 'Satmar'), ('Skver', 'Skver'), ('Viznitz', 'Viznitz'), ('Modern Orthodox', 'Modern Orthodox'), ('Karlin-Stolin', 'Karlin-Stolin'), ('Toldos Aharon', 'Toldos Aharon'), ('Sanz', 'Sanz'), ('Pupa', 'Pupa'), ('Klausenburg', 'Klausenburg'), ('Bostoner', 'Bostoner'), ('Other', 'Other')], max_length=50), blank=True, default=list, size=None),
        ),
    ]
