# Generated by Django 5.1.2 on 2025-03-12 15:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('temperament_analysis_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testquestionsubmission',
            name='test_session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_submissions', to='temperament_analysis_app.testsession'),
        ),
    ]
